analysis/urls.py
from django.conf.urls import url
from analysis import views

app_name = 'analysis'
urlpatterns = [
    url(r'^$', views.analysis, name='analysis'),
]

pictest/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from analysis import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    url(r'^analysis/', include('analysis.urls'))
]

analysis/models.py
from django.db import models

# Create your models here.

analysis/views.py
import os
import base64
from io import BytesIO
import time
import requests
from PIL import Image
from django.shortcuts import render, redirect
from .analysis import ela, judge


def index(request):
    return render(request, 'index.html')


def analysis(request):
    if request.method == 'POST':
        try:
            imgurl = request.POST.get('imgurl', None)
            imgurl = (imgurl.startswith('http://') or imgurl.startswith('https://')
                      ) and imgurl or 'http://' + imgurl if imgurl else None
            data = {}
            os.makedirs('tmp', exist_ok=True)
            filename = 'tmp/{}'.format(time.time())
            if imgurl:
                r = requests.get(imgurl)
                # fin = BytesIO(r.content)
                with open(filename, 'wb') as fin:
                    fin.write(r.content)
                data['rawimg'] = imgurl
            else:
                fin = request.FILES['file']
                # buf = BytesIO()
                with open(filename, 'wb') as fin2:
                    for chunk in fin.chunks():
                        fin2.write(chunk)
                # data['rawimg'] = 'data:image/png;base64,' + base64.b64encode(buf.getvalue()).decode()
                data['rawimg'] = 'data:image/png;base64,' + \
                    base64.b64encode(open(filename, 'rb').read()).decode()
            elaimg, data['diff'] = ela(filename)
            result = judge(filename)
            if result is True:
                data['result'] = '图片没有明显的修改痕迹。'
            elif result is False:
                data['result'] = '图片具有明显的修改痕迹。'
            else:
                if data['diff'] < 20:
                    data['result'] = '图片被 {} 处理过，但修改痕迹不明显。'.format(result[1])
                else:
                    data['result'] = '图片被 {} 处理过，具有明显的修改痕迹。'.format(result[1])
            data['elaimg'] = 'data:image/png;base64,' + \
                base64.b64encode(elaimg).decode()
            return render(request, 'report.html', data)
        except:
            return render(request, 'error500.html')
        finally:
            os.path.exists(filename) and os.remove(filename)
    else:
        return redirect('/')

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}图片检测{% endblock %}</title>
	<meta name="keywords" content="PicTest，图片检测，检测图片是否经过软件修改">
	<link rel="icon" href="/static/img/favicon.ico">
	<link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="/static/font-awesome/css/font-awesome.min.css">
	<link rel="stylesheet" type="text/css" href="/static/common/css/base.css">
	{% block style %}{% endblock %}
	<!--[if lt IE 9]>
  		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->
	<script src="/static/common/js/jquery.min.js"></script>
	<script src="/static/bootstrap/js/bootstrap.min.js"></script>
	{% block preScript %}{% endblock %}
</head>

<body id="page-top">
	<div id="wrapper">
		{% block nav %}
		<nav class="navbar navbar-expand-lg navbar-transparent">
			<div class="container">
				<a class="navbar-brand" href="/">
					<i class="fa fa-wpexplorer" aria-hidden="true" style="font-size: 60px;"></i>
				</a>
			</div>
		</nav>
		{% endblock %}
		{% block header %}{% endblock %}
		{% block main %}{% endblock %}
		{% block footer %}
		<footer class="text-center">
			<div class="container">
				<div class="row">
					<div class="col">
						Copyright &copy; {% now "Y" %} PicTest
					</div>
				</div>
			</div>
		</footer>
		{% endblock %}
	</div>
	{% block script %}{% endblock %}
</body>

</html>

templates/base_error.html
<!DOCTYPE html>
<html lang="zh-CN">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}图片检测{% endblock %}</title>
	<link rel="icon" href="/static/img/favicon.ico">
	<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
	<link rel="stylesheet" href="/static/common/css/base.css">
	<link rel="stylesheet" href="/static/common/css/base_error.css">
	{% block style %}{% endblock style %}
</head>

<body data-spy="scroll" data-target=".navbar-fixed-top">
	<div id="wrapper">
		{% block main %}{% endblock main %}
		<footer class="text-center">
			<div class="container">
				<div class="row">
					<div class="col">
						Copyright &copy; {% now "Y" %} PicTest
					</div>
				</div>
			</div>
		</footer>
	</div>
</body>

</html>

templates/error500.html
{% extends "base_error.html" %}

{% block title %}服务器错误{% endblock title %}

{% block style %}
<style type="text/css">
	.icon-font {
		color:orangered;
		font-size: 50px;
	}
</style>
{% endblock style %}

{% block main %}
<main>
	<span class="glyphicon glyphicon-remove-circle icon-font" aria-hidden="true"></span>
	<p class="text-center">你提了一个问题，被服务器拒绝了 O(∩_∩)O</p>
	<div class="text-center"><a href="/" class="btn btn-info">换张图片</a></div>
</main>
{% endblock main %}

templates/index.html
{% extends "base.html" %}

{% block style %}
<link rel="stylesheet" href="/static/uikit/dist/css/uikit.almost-flat.min.css">
<link rel="stylesheet" href="/static/dropify/dist/css/dropify.css">
<style>
	body {
		background: #F8FBFF;
		background-image: url('/static/common/img/bg.jpg');
		background-size: cover;
		-moz-background-size: cover;
		-webkit-background-size: cover;
		background-position: center;
		background-repeat: no-repeat;
	}
</style>
{% endblock %}

{% block main %}
<div class="container" style="margin-top: 120px;margin-bottom: 120px">
	<form action="{% url 'analysis:analysis' %}" method="POST" enctype="multipart/form-data" class="row justify-content-center"
	    onsubmit="return check();">
		{% csrf_token %}
		<div class="col-xs-12 col-sm-8 col-md-6 col-lg-6 col-xl-6" id="input-form">
			<input id="input-file" type="file" name="file" data-show-upload="true" class="dropify" autofocus/>
			<a id="switch_btn" href="javascript:showInput()" class="uk-display-block uk-margin-top uk-text-center uk-text-bold">输入图片地址</a>
			<!-- <input id="input-url" type="input" name="file" class="form-control" style="display:none;"/> -->
			<div id="input-url" class="input-group" style="display:none; margin:10px 0;">
				<input type="text" name="imgurl" id="imgurl" placeholder="请输入图片地址" class="form-control search-group fc-clear" autofocus>
				<span class="input-group-btn">
					<button class="btn btn-info text-center" type="submit">分析</button>
				</span>
			</div>
		</div>
	</form>
</div>
{% endblock main %}

{% block footer %}
<footer class="text-center">
	<div class="container">
		<div class="row">
			<div class="col">
				Copyright &copy; {% now "Y" %} PicTest
			</div>
		</div>
	</div>
</footer>
{% endblock %}

{% block script %}
<script src="/static/dropify/dist/js/dropify.js"></script>
<script src="/static/uikit/dist/js/uikit.min.js"></script>
<script>
	$('.dropify').dropify({
		messages: {
			'default': '<h3 class="uk-h4">图片上传</h3>注：将图片拖拽到此处或点击上传',
			'replace': '拖拽或点击上传以覆盖',
			'remove': '删除',
			'error': 'Ooops, 出现问题了.',
			'upload': '开始上传',
		}
	});

	function check() {
		if (document.getElementById('input-url').style.display == 'none') return true;
		var text = document.getElementById('imgurl').value;
		if (text === null | text.replace(/(^\s+)|(\s+$)/g, '') === '') {
			alert('请输入图片地址！');
			document.getElementById("imgurl").focus();
			return false;
		}
		return true;
	}

	function switchType() {
		var dom = document.getElementById('input-file');
		dom.removeAttribute('data-show-upload');
		dom.className = 'form-control';
		dom.type = 'input';
	}

	function showInput() {
		var inputBox = document.getElementById('input-url');
		if (inputBox.style.display == 'flex')
			inputBox.style.display = 'none';
		else {
			inputBox.style.display = 'flex';
			document.getElementById('imgurl').focus()
		}
	}
</script>
{% endblock %}

templates/report.html
{% extends "base.html" %}

{% block style %}
<style type="text/css">
    img {
        width: 100%;
    }
    h2 {
        margin-top: 20px;
        color: #4fb1f7;
    }
    h5 {
        margin-top: 20px;
    }
</style>
{% endblock style %}

{% block main %}
<div class="container">
    <div class="row">
        <div class="col text-center text-info">
            <h2>图片检测报告</h2>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="alert alert-primary" style="margin-top: 30px;" role="alert">
                {{ result }}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <h5>ELA对比图</h5>
        </div>
    </div>
    <div class="row">
        <div class="col text-center">
            <a href="{{ rawimg }}" target="_blank"><img src="{{ rawimg }}" alt="原图" /></a>
        </div>
        <div class="col text-center">
            <a href="{{ elaimg }}" target="_blank"><img src="{{ elaimg }}" alt="ELA图" /></a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <p class="text-center text-primary" style="margin-top: 30px;">ELA diff: {{ diff }}</p>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <p class="text-center text-muted">右图中较亮的部分可能经过了修改。</p>
        </div>
    </div>
</div>
{% endblock main %}

{% block footer %}{% endblock %}